### ISSUE TITLE
Nested permissions

### ISSUE THREAD

**Issue by Plitzz** [arenanet/api-cdi#117]
Yesterday I noted with delight that under the endpoint "/account" the last point is output fractal_level.

Unfortunately, however, only if the API key is authorized progression.

Is there a reason for this?

It is also extremely annoying from my guild members repeatedly demand new API key because the permissions are changed or get worse.

I do not believe that there is a solution that makes the extension of the existing API keys possible, right?

greeting

Markus

**Comment by lye** [comment]
Sorry for the delay responding; I've been really bad keeping everything up-to-date in github.

The intent is that API keys don't retroactively gain abilities after assignment. When I set up all the permissions, I tried to make sure that everything we'd add in the future is in the description on the account site so that there weren't any surprises down the line (e.g., "why can this site suddenly see my TP transactions?"). In some cases, it doesn't make as much sense (as in this case), but the intent was to make it flexible enough for users to feel comfortable granting access to the parts of their account they want to share.

I agree that it's kind of a mess w.r.t getting new API keys (I've had to regenerate my gw2efficiency key half a dozen times due to new permissions), but the good news is that I don't think there's any more to add (because it's already bad/complex enough).

In any case, I consider the current system to be set in stone, so I'm gonna close out this issue.
