### ISSUE TITLE
/v2/achievements/daily seems to be incorrect

### ISSUE THREAD

**Issue by kasoki** [arenanet/api-cdi#120]
I thought /v2/achievements/daily would use the NA timing ( #96 ) which is why they're incorrect for EU players but one of my users reports that they're incorrect for NA players as well ( https://github.com/kasoki/LoginWars2/issues/8 ).

**Comment by lye** [comment]
I think the API server is on some weird clock or something. There's a fix in the works but I'm not sure I can land it until December due to holidays and such.

**Comment by poke** [comment]
I don’t really know where this NA vs EU timing idea comes from, since the reset time of dailies has always been midnight UTC for *everyone* (it has been like that since GW1).

I have been tracking the dailies using the API now for three weeks, confirming it in-game every day on both a EU and NA account. What I saw *all the time* is that the daily API simply shows the dailies for *the next day*. This happens consistently at any given time. As such, to get the current dailies, I always look at the ones from the day before. This hasn’t shown me the wrong dailies even once.

Now I haven’t been around at midnight UTC often to see if the API switches exactly at that point, but the few times I was awake around that time confirmed that it correctly works as described above, always listing tomorrow’s dailies.

Since I think listing tomorrow’s dailies is particularly useful, I would not like to see this fixed to show today’s dailies. I could totally live with how it is right now, but a good alternative would probably to have two separate endpoints for today’s and tomorrow’s dailies.

**Comment by AlexSwensen** [comment]
I agree that it would be nice to see tomorrows daily's as well as the current ones.
As for the point at which the API switches, it happens at midnight UTC as well.

**Comment by kasoki** [comment]
Interesting... why do we even have the [na, eu] split then? I was assuming that they do have different reset times.

**Comment by AlexSwensen** [comment]
I am assuming its like lye said, and that there is a problem with the API server thats serving that information. As for the NA vs EU times, i can't confirm that. I am on NA, and haven't yet bothered to do anything with an EU account as of yet.

**Comment by poke** [comment]
You seem to miss my point: There is no problem with the API server. The only “problem” would be that it always shows tomorrow’s dailies instead of todays…

> why do we even have the [na, eu] split then?

That’s kind of my question. Why was this apparent split ever brought up (and is suggested as a possibly coming solution)? Where did this come from? There is no difference in-game between NA and EU as far as dailies go. They reset always at midnight UTC, regardless of your server location. I and hundreds other people can confirm that. And as for the API, it seems that it’s perfectly in sync with that reset time at midnight UTC too.

**Comment by AlexSwensen** [comment]
I believe this issue is much more along the lines of which dailies are shown (tomorrows vs todays) rather than any apparent "split" from NA vs EU.  Along those lines, i do not miss your point, however i believe that becomes a moot point with a resolution to this issue.

**Comment by lye** [comment]
> I don’t really know where this NA vs EU timing idea comes from, since the reset time of dailies has always been midnight UTC for everyone (it has been like that since GW1).

> Why was this apparent split ever brought up (and is suggested as a possibly coming solution)? Where did this come from?

That was my bad -- there isn't any difference for daily resets. I got confused because there *is* a difference for WvW reset times. I'm going to remove that bit since it doesn't make any sense.

> I believe this issue is much more along the lines of which dailies are shown (tomorrows vs todays)

The main issue, as I see it, with displaying tomorrow's dailies is that they might change (e.g., due to a patch).

Anyway, the backend fixes are in as of an hour ago, so I should have the endpoint spitting out the correct data sometime this week.

**Comment by lye** [comment]
> If you do that, please leave another endpoint that still gives tomorrow’s dailies.

Should be pretty straightforward. Suggestion for an endpoint name? `/v2/achievements/tomorrow` or `/v2/achievements/daily/tomorrow` or /v2/achievements/daily?tomorrow`? None of them really feel right to me. @tivac halp.

**Comment by dr-ishmael** [comment]
/v2/achievements/daily/current and /v2/achievements/daily/next?

Would it possible to parameterize it to pull achievements for N days in the
future? /v2/achievements/daily?offset=N (default N = 0)

**Comment by tivac** [comment]
@lye sorry I don't have any URL structure I love for that.

`/v2/achievements/daily` and `/v2/achievements/daily/next` seem the most innocuous to me. We shouldn't show multiple days in advance IMO since that isn't exposed in the game UI and may change due to content updates.

**Comment by kasoki** [comment]
Not sure if it's that bad if a daily in the future changes because the API will also update if that happens.

**Comment by lye** [comment]
Just as a note; I deployed a new version of the code that should behave correctly at reset. Gonna keep an eye on it and make sure it does the right thing in the live environment.

**Comment by poke** [comment]
I noticed that the `/daily` endpoint already switched to today’s daily a few hours ago. Does that new deployment already include an endpoint for tomorrow’s dailies?

**Comment by lye** [comment]
Not yet, no. I'll probably add it later this week.

**Comment by kasoki** [comment]
Just confirmed that the data is indeed correct now, thanks ;).

**Comment by lye** [comment]
Just confirmed that it updated properly on reset too. Hurrah for no surprises on live today.
