### ISSUE TITLE
Guild member presence info.

### ISSUE THREAD

**Issue by lye** [arenanet/api-cdi#144]
Would be useful to have either the online/offline (or last online) info in the guild member data, in addition to the current map. [Forum thread](https://forum-en.guildwars2.com/forum/community/api/New-endpoints-guild-ranks-members/5870470).

**Comment by Fishrock123** [comment]
Oh this would be nice.

**Comment by queicherius** [comment]
:+1:

**Comment by cawhouston** [comment]
ditto, would be of real interest

**Comment by lye** [comment]
To transcribe from the forum thread,

> Ideally also if they are repping the guild or not, so perhaps three states: Repping, NotRepping and Offline. If that isn’t possible maybe a Last Rep date on top of the last log in?

**Comment by lye** [comment]
So, some privacy concerns were raised in a gitter discussion about widely exposing presence info without granular controls (e.g., you may not want your guild leader (or anyone the leader designates) to see a history of all your location data). The main thing we want to avoid is player positional data being exposed without explicit opt-in.

The solution I'm looking at is two fold:

 * Add a new scope, `presence` or `location` or something that gives access to the API key owner's presence info (via e.g., `/v2/account/location`).
 * Add an in-game per-guild toggle (default off) that allows that guild's API key to see your presence info (via e.g., `/v2/guild/:id/members`). Any members without that option enabled will not have their presence info shown in the member list.

As an additional note, the "invisible" presence setting affects the same data source that the API would use, so setting yourself to invisible is going to disable all the API bits as well.

**Comment by poke** [comment]
For those interested in the actual discussion, read [from here](https://gitter.im/arenanet/api-cdi?at=568d4485e8598dd060156afe).

**Comment by chrish16** [comment]
I've been trolling through old discussions as I (im)patiently await the contacts API. I figured looking at the guild members API would be a good idea since the guild list is very similar in behavior to the contacts list in game.

Seeing your comments @poke, in the aforementioned gitter chat, leave me very uneasy. It reads very paranoid, as if you're trying to create a problem before there even is a problem- and I think that any of your suggestions to create more walls to this data will set a dangerous precedent for the contacts API and most likely render it completely useless.

The only example you used to illustrate a potential "privacy violation" was that of a WvW guild:

> Imagine a hardcore WvW guild monitoring their users automatically to enforce some odd rules.

I'm actually in a large WvW guild in tier 1 so I gathered the leader and a group of officers and presented the gitter chat. Everyone said something to the effect of what @lye said:

> eh, the rules are usually "be on TS"
> and then there's teasing if you're caught in a PvE zone

@lye went on to say: 

> @poke eh, in my experience in the post-guild-chat update, the requirements are usually "this is our raid schedule, make N/M raids/week"

That is exactly my experience as well.

My group also mentioned that currently there is no way to escape the policies of the "super hardcore" WvW guilds that require people to attend raids on specific days. What they do is check players' achievement points, and if the number changes it means that, no, you're not "on vacation," you're playing while invisible and avoiding attending mandatory raids.

Other people in the gitter chat pointed out that if options/permissions are made to opt out of the guild API, **serious guilds will require opting in anyway**. Meaning adding such permissions will do effectively nothing to protect the "privacy" of the player. In fact I think it would have as much effect as a blog post/announcement letting players know that guild leaders could **potentially** look at the guild roster while not playing the game. It boils down to: you shouldn't be in a guild if you don't agree with its policies or trust its leadership.

-----

You also said later:

> I just think that the API shouldn’t expose things just because they are exposed within the game client.

I have to completely disagree. What is the point of the API if it should have huge holes in data? When ArenaNet announced work on these APIs a few years ago it was hyped that they would give rise to complex (and useful) out-of-game applications.

Right now the guild members API gives a list of member account names, the ranks of those members, and the date they joined the guild. **The most complex application that can be developed with this information is a list of guild members sortable by rank and join date.** Why shouldn't the API also tell said members' online/offline status and current map? How is this a violation of privacy when I can open up the game client, press G, and get this information immediately? If anything the API is already more limited than the game because it at least requires authentication by the guild's leader. This information is freely available to **anyone** in game.

(Not to mention, and this is why I truly believe there is no point in leaving this information out the API, players have the ability to log in invisibly.)

-----

I think the guild members API (and the contacts API whenever that becomes a thing) should include the current information, and:

* Online/offline/away/lfg status.
* Name of currently utilized character (right now the API shows account name).
* Level and profession (freely available in game by hovering over a name in the list).
* Current map.
* IP of the current map (freely available in game by typing /ip) to distinguish between instances of the same map.
* Achievement points.
* If the player is in a party or a squad (freely available in game by right clicking on a name and seeing if it says join party or join squad).

**Comment by Sajaki** [comment]
+1 @chrish16 exactly this. guild Api is way too limited now to warrant app development. Look at battlenet guild api. I need that level of detail.

**Comment by Aralicia** [comment]
@chrish16 While I agree with most of what you said (and I'm a proponent of the API giving more info about the guild members), I find myself bound to reply to your implicit remark : "what's the point in leaving out of the API something already freely available ingame ?"

There is one big difference between data available ingame, and data available through the API : the possibility for automation. While a guild member can now the status of another member at any given time, he can't continuously track the status of all members 24/7. This would allow for more effective monitoring tools for the guild leaders. 

Maybe you are ok with the guild leader being able to know exactly when you are online and when you are not, and the your exact ratio of participation on each map&mod, but I know of more than a few people who would be creeped out by this. 

This possibility for automation can give very powerful tools for personal use (for example, by monitoring simultaneously your location & your currencies, you could be able to determine which map/mode gives you the most bucks for your time), but it also create a more intrusive mode of monitoring players, which shouldn't be considered as ok to have always active.

I believe that the privacy concerns shouldn't prevent us to have access to this feature, but each member should have the option to opt-out on this. Sure, hardcore guilds may require it - it's their right - but other, more laid-back guilds would allow its members to join or not the guild-wide tool as they please.

**Comment by chrish16** [comment]
@Aralicia I understood the earlier arguments about automation the first time but what you and @poke seem to forget is that players have complete control of the appearance of their online status in game and I imagine going invisible in game would also make you appear offline in any contacts-related APIs. Meaning, any player right now could thwart whatever efforts to "track them 24/7" if they so desired.

**Comment by Aralicia** [comment]
@chrish16 So the solution you propose to not be tracked to through the API is not to be available at all to others ingame ? And what if you would want to allow one guild to track you and not another ? The current solution you propose is a hack on another functionality that doesn't meet the needs a better design could offer.
Especially in the domain of privacy, we should strive to offer the best implementation possible, not a "you could just use a PS3 to cook your steak" solution.

**Comment by chrish16** [comment]
@Aralicia I see this playing out in one of two ways.

1: ArenaNet adds online/offline status to the guild API and doesn't give players any opt-out "privacy" controls:

John Doe joins a guild. He browses reddit one day, sees a thread about the new API capabilities and realizes guilds could potentially see whether he's online without loading up the game. He asks the guild leader, "Hey are you monitoring your guild members with the new API?" The leader says "Yes, we are." John Doe isn't comfortable with this, he doesn't trust this guild or like that they can see he logs in at 3AM every now and then. He leaves the guild.

-----

2: ArenaNet adds online/offline status to the guild API, but only after taking 6 months to go through various departments to add an opt-out check box to the Options [F11] interface in the game client.

John Doe joins a guild. One day the guild sees an announcement about the new capabilities of the API and leadership decides they want to make an application to monitor guild activity. They realize players can opt-out of monitoring. They make it mandatory policy for all members to opt-in. John Doe isn't comfortable with this. He leaves the guild.

-----

Alternative ending to both scenarios: John Doe opts in but logs in invisibly when he wants to play at 3AM.

-----

My main point here is that guilds who want to "monitor players 24/7" are going to do that **anyway**. Is there really a point to, or any benefit to adding an opt-out for APIs that show online status?

Personally I've always thought online/offline status capability was enough to constitute "privacy" controls in virtual worlds.

**Comment by Aralicia** [comment]
@chrish16 
Guild #3 is a guild that maintain a website. They don't actually want to monitor user activity, but to would like a widget on this site that show "who's online", because it's a cool feature !

John doe like this guild, but doesn't really want to appear on the widget.
Now, he must either :
- leave the guild; not good for him or the guild, since they liked each other.
- login in invisible; not good, because it seriously hampers his ability to interact with the other members of the guild, and other guilds he may be a member of.
- accept that he will show; not good because he doesn't want to.
- beg for the dev of the guild's website to manually add an opt-out option in the widget's code.

The issue could have been easily fixed if John Doe had the possibility to simply tells the API that he doesn't want to appears on it. 
Sure, devs querying the API could add their own opt-in/out filters on it, but require additionnal code and an authentication system for every new site/app made.

The point is that all uses of this endpoint aren't going to be for hardcore monitoring, and a guild making use of this endpoint may do so for other reasons than Big Brothering the members. For such guilds, opting in/out API visibility is totally acceptable, and wouldn't be penalized by exclusion. Moreover, even in guilds that does monitoring, this monitoring may be required only for a part of the members (for ex,, only for the main PvP or Raid teams, but not the rest of the guild).

You can't presuppose that this endpoint will only ever be used by guild with mandatory monitoring.

But, even taking your point ("guilds who want to "monitor players 24/7" are going to do that anyway."), you could extend it to : what's the point for the online status at all anyway ? After all, they already can monitor you through alternate means.

The ability to control what you show out of game is has important as the ability to control what you show ingame, but are also distinct contexts, and for some players would important to separate them.

**Comment by cawhouston** [comment]
What is the status of this feature? Will it be provided? My understanding that through an API  one could get the number of people logged on and representation info.

**Comment by Sajaki** [comment]
again, this is a breaking issue for me to be interested at all in the GW2 api.

**Comment by Keeky** [comment]
Any update on this? I couldn't find any information about it being implemented.

My two cents on the privacy issue: As soon as an opt-in or opt-out is added, the data isn't really reliable for a bunch of tools anymore. So I'd leave the decision up to the guild leader. To address the privacy concerns, I'd propose to add another rank permission for it. "Show up in external tools" or something. That way the guild leader still has control over the data and it's transparent to members as everyone sees if this permission is enabled for their rank.

Just speculation, but aside from adding it to the ingame UI it shouldn't be difficult to implement too, as the rank permissions are already available to the API.

I'd like to see the same information added to `/v2/guild/:id/members/` as ingame (online status, map and is a member is representing at the moment)

**Comment by lye** [comment]
> Any update on this?

`ENOTIME`, unfortunately.

**Comment by Archomeda** [comment]
[Archived forum ref.](https://gw2developers.github.io/forum-backup/New-endpoints-guild-ranks-members/)
