### ISSUE TITLE
"Gilded Hollow" Needs To Be Deduplicated

### ISSUE THREAD

**Issue by FrederikNS** [arenanet/api-cdi#153]
When retrieving `/v2/continents/1/floors/0` I get 6 different zones with the name "Gilded Hollow". The data in all the 6 different "Gilded Hollows" are identical, only the `ids` are different.

The 6 ids are `[1068, 1101, 1107, 1108, 1121, 1125]`

The same goes for the instance "Claiming the Gilded Hollow", which has 4 identical objects, with the ids `[1066, 1088, 1098, 1122]`

It seems that the same data is reflected in the `/v2/maps` api.

Further more, the "Gilded Hollow" is not present at all in the floors 1, 2 and 3.

**Comment by queicherius** [comment]
[There are multiple copies of each guild hall map because they’ve got different population caps.](https://forum-en.guildwars2.com/forum/community/api/API-2-maps-multiple-and-missing-ids/first#post5781735)

**Comment by FrederikNS** [comment]
@queicherius Thanks for the link, it makes pretty good sense, but it is still pretty useless, is there any chance that the duplicates can be hidden from the API as they don't really serve any purpose? or do I have to manually keep a blacklist to clean up the API output?

**Comment by lye** [comment]
Manual blacklist is the only way to do it; it'd either be on our side or yours.

I have a handful of reasons I'd rather it be on the application side, but none of them are particularly compelling (e.g., it's altogether possible that the different map instances will diverge; if they don't after changes are made, it's probably because new maps were copy-pasted from the changes and ids might change). I don't disagree that the way it's implemented is, uhh, unintuitive at best, but in this sea of madness I've got to pick my battles and I'm not sure how deep this particular iceberg goes. I'd rather steer clear.

Sorry :(

**Comment by FrederikNS** [comment]
Oh well, too bad. Thanks for the clarification.

**Comment by lye** [comment]
As a note (since this was brought up in gitter recently); I believe the GH maps are duplicated once for each instance size. Map caps aren't dynamic at all, so the implementation basically just uses multiple copies of each map with a separately configured mapcap and connects them in some magical way that I haven't yet figured out.
