### ISSUE TITLE
/v2/professions - Starting heal skill and racial skills are missing

### ISSUE THREAD

**Issue by Eearslya** [arenanet/api-cdi#302]
Already discussed this with @lye in gitter, but creating this to help keep track.

It's possible to get a list of a profession's weapon and slot skills by parsing the `training` object, but this ends up leaving out the heal skill the class starts out with, as this is given by default and not trained for.

**Comment by lye** [comment]
Expanded this to include racial skills since that's a related issue -- the underlying problem is that the existing skill enumeration works by going over all the training tracks to see which skills can be unlocked. Since the starting heal skill and racial skills aren't on the training tracks (because they're implicitly unlocked) they're not flagged as okay to put on the API.

**Comment by darthmaim** [comment]
Same for the profession mechanics (for example attunements), would be nice if they were included in/v2/professions.
