### ISSUE TITLE
Stat-selectable items "stats" issues

### ISSUE THREAD

**Issue by queicherius** [arenanet/api-cdi#316]
**Some items have an empty `attributes` array and a stats `id` that doesn't exist.**

- Ingame: http://i.imgur.com/0LMhldA.png
- API call: https://api.guildwars2.com/v2/characters/Shar%C3%B4x?access_token=BFCDF695-5D2D-114F-B6A1-FC2466C79A2692147B4D-20B1-4C45-BA25-43808695A041

```js
"stats": {
  "id": 1046, // no such id
  "attributes": {} // wat
}
```

---

**For some items the `stats` dont show up at all**

- Ingame: http://i.imgur.com/cKizwIg.png & http://i.imgur.com/ikESmBi.png
- API call: https://api.guildwars2.com/v2/account/bank?access_token=0679ED44-0170-B548-AFE8-30C598C7A0C38D8A8DC9-75FE-4E19-ABA6-58B0760CE61B

```js
// first image, stats missing
{
  "id": 50063,
  "count": 1,
  "skin": 2379,
  "infix_upgrade_id": 161,
  "upgrades": [
    24498
  ],
  "binding": "Character",
  "bound_to": "Lénex"
},
// ...
// second image, stats ok
{
  "id": 50063,
  "count": 1,
  "upgrades": [
    24498
  ],
  "binding": "Character",
  "bound_to": "Nephiruel",
  "stats": {
    "id": 161,
    "attributes": {
      "Power": 30,
      "Precision": 21,
      "CritDamage": 21
    }
  }
}
```

---

**Some items have the wrong `attributes` values. Suspected are ascended items with hidden jewels.**

- Ingame: https://files.gitter.im/arenanet/api-cdi/b5YT/Naamloze-afbeelding.png
- API call: https://api.guildwars2.com/v2/characters/Reiga%20Fiercecrusher?access_token=4B9D7AF6-EC5D-6C49-A2B6-0113BFB659D3699D392E-A81F-4CB6-B2FA-6AF35C9FFE36

```js
"stats": {
  "id": 584,
  "attributes": {
    "Power": 31, // should be 63
    "Precision": 22, // should be 40
    "CritDamage": 22 // should be 40
  }
}
```

**Comment by tivac** [comment]
I see you :+1:-ing your own issue :suspect:

**Comment by queicherius** [comment]
@tivac Caught me. :disappointed: I am just so excited for this, having the exact same attributes calculated on efficiency as in the game is a pet-peeve of me.

**Comment by lye** [comment]
Okay, so for the three cases:

## Items with empty stats objects

So, it's kind of incredibly annoying that I didn't notice this earlier. An `itemstats` object has an `attributes` field (which is scaled as described) -- all the ones that have empty `attributes` via the API instead sidestep this whole system and apply a hidden buff with a script. The hidden buff, in a lot of these cases, just adds a flat modifier to the attributes (though I presume it can also add scaled modifiers).

I'm gonna have to sort this out, but I suspect `itemstats` objects will get an additional field to indicate this. 

## Stats not showing up

This is related to #313 -- some choosy stat items use `itemstats` that are not the default on anything -- because of that, they weren't picked up by my "find all referenced itemstats" script. I'll need to add an additional field to `/v2/items` to indicate which stats are available for selection, then re-enumerate `/v2/items` and add the missing entries to the `/v2/itemstats` whitelist.

## Wrong attribute values

This ties into the first one -- for these items, there's an `attributes` field that has the scaling attributes *and* a hidden buff that adds unscaled attributes (which is how most jewels and stuff work). The unscaled attributes aren't currently added in. This should be fixable without changing any endpoints -- just need to adjust the backend implementation to consider the buffs when determining the stat values.

**Comment by lye** [comment]
Okay, I've got a fix for this in the works -- due to the release process it's gonna take awhile to make it live (release after next, I think). The major changes here are that

 * There's gonna be a new field on `/v2/itemstats` that includes unscaled stat additions. Maybe `attributes_static` or something. Works the same way as the `attributes` object, except that it has raw unscaled values.
 * All of the ascended items that have busted stats (because of the implicit jewel) will start returning the correct stats. I think a couple of applications are parsing the description string -- that'll be totally unnecessary after this lands. There was an existing issue for this, #48, that I never wanted to touch because the code to handle it is exceptionally edge-casey. I guess I'm a bit more gung-ho this year.

**Comment by Archomeda** [comment]
Just to add a little related bug to point 2 (as far as I can match the example from @queicherius).
Anyway, I've got 2 "identical" Spectral Jujus and 2 "identical" Malicious Energized Loops. However, they are apparently not as identical as one would think. I've bought 1 of both some time ago, and then 1 of both again some time later. And apparently they are somehow different.

When both items are equipped, the following is shown on the API (rings as example):
```javascript
{
    id: 77272,
    slot: "Ring1"
},
{
    id: 77272,
    slot: "Ring2",
    stats: {
        id: 1130,
        attributes: {
            ConditionDamage: 81,
            Power: 81,
            ConditionDuration: 44,
            Precision: 44
        }
    }
},
```

When they are in my inventory again (accessories as example):
```javascript
{
    id: 77413,
    count: 1,
    infix_upgrade_id: 1130,
    binding: "Account"
},
{
    id: 77413,
    count: 1,
    binding: "Account",
    stats: {
        id: 1130,
        attributes: {
            ConditionDamage: 67,
            Power: 67,
            ConditionDuration: 37,
            Precision: 37
        }
    }
},
```

As a side note, all these trinkets have Viper as selected stats. [API call](https://api.guildwars2.com/v2/characters/Karza%20Bloodwalker?access_token=4B9D7AF6-EC5D-6C49-A2B6-0113BFB659D3699D392E-A81F-4CB6-B2FA-6AF35C9FFE36) (not reliable since I play on this character and the items might move around).

It seems that one is missing the `infix_upgrade_id` and the other the `stats` field. Now I don't know if this is because there are two of each item (somehow when I change order in my character slots, the actual item order on the API seems to stay the same) or just because one of each is older than the other and the item has changed at some point.

**Comment by lye** [comment]
There was an issue where only the first of each item-upgrade pair would be processed (the `infix_upgrade_id` shouldn't be exposed, whoops). The fix for that will go out sometime this week. The other bits are going to take some time to filter through the release cycle.
