### ISSUE TITLE
/guild/:id/log/ timestamps are different for every request

### ISSUE THREAD

**Issue by opr** [arenanet/api-cdi#331]
If I make a request to check my guild log, the timestamps are different every time:

Request 1: 

```
...
  {
    "id": 2950,
    "time": "2016-06-14T21:08:40.724Z",
    "type": "treasury",
    "user": "KelsteNa.7903",
    "item_id": 19684,
    "count": 5
  },
  {
...
```

Request 2:
 ```
...
 {
    "id": 2950,
    "time": "2016-06-14T21:08:41.291Z",
    "type": "treasury",
    "user": "KelsteNa.7903",
    "item_id": 19684,
    "count": 5
  },
...
```

**Comment by lye** [comment]
Hmm, that seems a bit weird. Can you provide your guild GUID?

**Comment by opr** [comment]
yeah, it's causing a few hiccups in my application but nothing too awful, guild ID is 28555027-D135-E411-AEFB-AC162DC05865

**Comment by lye** [comment]
So a backend component is transferring a relative time across the network (which the frontend converts to the absolute time returned) -- because of this `time` might be a bit flaky when the network delay exceeds 1 second (which happens sometimes).

I've adjusted the conversion from relative -> absolute time a bit (basically lopping the resolution down to seconds) so it *should* be a bit more stable, but they're definitely not gonna be constant. The `id` field is the only guaranteed unique identifier.

**Comment by opr** [comment]
Thanks for the note, this is probably going to be quite helpful - are IDs of newer events always guaranteed to be larger than older events?

**Comment by lye** [comment]
Mostly yes but technically no. The ids are stored internally as a `uint32_t` and will eventually wrap back to `1` (they'll never be zero). I'm not sure if that's happened for any guild.
