### ISSUE TITLE
"binding" is missing for equipment, material storage & bag items

### ISSUE THREAD

**Issue by queicherius** [arenanet/api-cdi#374]
- The equipment of characters should have the same `binding` flag as in the inventory of characters, since the items can either be character bound (exotic and below) or account bound (ascended and legendary).
- The bag items (the actual bags, not the inventory) need a `binding` flag too. This can either be soulbound (the starting container), account bound (e.g. fractal bags) and no flag (the tp-tradeable bags)
- The material storage items are also missing a `binding` flag ("account" for the daily cooldowns, obsidian shards, ...)

**Comment by lye** [comment]
> The equipment of characters should have the same `binding` flag as in the inventory of characters.

This will be fixed with the next deploy.

> Bag items / material storage `binding`.

This one is a bit more convoluted -- the way binding works is that the item flags are applied first, then any flags on the item instance are applied *over* them. While technically any item can have binding flags, realistically only equipment ever does (items that bind on use typically are containers that give you a bound version of the item -- not sure why really).

But maybe I'm just being lazy, would make more sense to have it be uniform.
