### ISSUE TITLE
Infused and Attuned flags

### ISSUE THREAD

**Issue by Darqam** [arenanet/api-cdi#525]
As it stands, there is no straightforward way to figure out if an item has been infused, attuned, or infused AND attuned.

In most cases it's possible to look at the name for the key words, but this isn't a consistent solution. Looking at the amount of infusion slots only works to say if the trinket is infused OR attuned. In the case of back pieces this works fine since they can only be infused, but for rings it provides no answer.

To that extent I would like to suggest adding a `Infused` and `Attuned` flag if the item qualifies. Bonus points if it's possible to have flags showing if the item CAN be infused or attuned, but that seems quite a bit more complicated.

**Comment by lye** [comment]
Bleh, the infused/attuned status isn't stored in any structured way; the items are totally unrelated except for sharing a name and having a mystic forge recipe for attunement/infusion. Annoyingly, the [name doesn't always change](https://wiki.guildwars2.com/wiki/Rurik%27s_Engagement_Ring_(attuned_and_infused)), and I'm really hesitant to try parsing mystic forge recipes for metadata. It might not be that bad since all the recipes for attunement/infusion require three common ingredients, hmm.

**Comment by lye** [comment]
[Flags are live](https://api.guildwars2.com/v2/items/79460).
