### ISSUE TITLE
Provide an endpoint for effects!

### ISSUE THREAD

**Issue by valento92** [arenanet/api-cdi#565]
Like [this](https://wiki.guildwars2.com/wiki/Deadly_(Archetype))! There's always a name, icon, type, description and facts involved. =)

**Comment by DomGrieco** [comment]
Agreed, include boons/conditions and all the other good stuff.

**Comment by apoch** [comment]
It would be cool to be able to expose buffs (which is our internal name for status effects/etc.) and have a way to examine them from the API.

The tricky part is that buffs are a very flexible and rich system in our game. We use them for a *lot* of stuff. There are over _24,000_ different buffs in the game right now. Obviously the huge majority of those are not intended for players to ever see or know about. This is a major challenge because we don't have a way to distinguish between "buff players should see in the API" and "buff that shouldn't be visible."

Whitelisting them one at a time is clearly not practical, and there's a lot of things we can't just expose. Barring a really creative approach that I'm not thinking of, I don't think this is something we can really do realistically.
