### ISSUE TITLE
Daily dungeon completion does not reset correctly

### ISSUE THREAD

**Issue by queicherius** [arenanet/api-cdi#640]
If a user completes a dungeon, the dungeon completion will persist in `/v2/account/dungeons` **through daily resets**:

> on Sunday, I did Hodgins path
> yesterday I only logged in for daily chest
> I haven't logged in today
> the API shows me that I did Hodgins

Apparently logging in correctly resets the state:

> Logging in once I got home reset them for today

**Comment by Aonwy** [comment]
Daily reset is an in-game concept, and so the state of the account is based on the most recent login of that account. This is working as intended.

**Comment by Aonwy** [comment]
Daily reset is an in-game concept, and so the API will not update until a player logs in and does something. Can you provide more information around what happened, please, including a timeline and what exactly the player saw at each phase?

**Comment by queicherius** [comment]
> Daily reset is an in-game concept, and so the API will not update until a player logs in and does something. 

I would say that this is a bug.
Is there a way that you can flag the information in some way? Here is what I would expect:

1. The user does dungeons
2. The API shows his dungeons
3. The user does not log in after daily reset
4. The API knows that the data is before daily reset, therefore stale, impossible that the user did any dungeons yet, and just serves an empty array
5. The user logs back in
6. The API after updating the ingame state shows that the user did not do any dungeons yet (empty array)
7. The user does more dungeons
6. The API now reflects the newly done dungeons

Here is what actually happened:

1. The user does dungeons
2. The API shows his dungeons
3. The user does not log in after daily reset
4. **The API shows the dungeons from the day before** 💥 
5. The user logs back in
6. The API after updating the ingame state shows that the user did not do any dungeons yet (empty array)
7. The user does more dungeons
6. The API now reflects the newly done dungeons

**Comment by apoch** [comment]
I think the exact sequence of events is super important here, because of how the game works. I'm going to run with this in a very pedantic and picky way, because I think the specifics can be explained. If I have misread your timeline please let me know because then there is a bug :-)

When you are not logged in to your account, nothing in it changes (generally speaking). There is no process that bumps your daily dungeon list, for example. Those things are updated when the next login happens, and in no other circumstances. API queries reflect that, in that they show the last recorded state of the account, not the state of the account as if it had logged in.

Put another way: the data in the account is not adjusted by API queries (as is right and good). So if we leave an account alone for a month, it will show month-old data, because the thing that is allowed to update that data (the game) has not been asked to do so (i.e. we didn't log in).

So if I can be really pedantic about the timeline, this is the game's perspective:

1. Day 0 - User does some dungeons
2. Day 0 - API shows those dungeons correctly
3. Day 1 - User does not log in today
4. Day 1- API shows Day 0 dungeons (which would be correct behavior)
5. Day 2 - User logs in again
6. Day 2 - Game says "Hey you logged in, I should update your dungeons. Oh look, you didn't do any yet! I will report that your array of runs is empty." (Again, correctly.)
7. Day 2 - API query shows empty array (correctly)
8. Day 2 - User plays some dungeons
9. Day 2 - API data reflects the played dungeons (correctly)

Sorry if this is a bit finicky. I hope the background detail helps explain our perspective on this and why we consider it expected behavior. And of course again if I have misread a detail please do let me know, there is always a chance that something is wrong and I'm not seeing it yet :-)


Thanks!

**Comment by queicherius** [comment]
> 4. Day 1- API shows Day 0 dungeons (which would be correct behavior)

Yes, this is the step that I, as a user, would expect an empty array.

> Those things are updated when the next login happens, and in no other circumstances. 

While I knew the technical side of things before I opened this issue and I can completely understand the reasoning, I would still call this a bug since the API is giving back incorrect information. 

Even with the incorrect information being the expected behaviour, I don't think it is very intuitive, based on the fact that I get about 4 bug reports from users that their dungeons did not reset correctly. In the same vain, I would expect daily achievement completion (#175 etc) to reset as well, if we get it at some point.

> Put another way: the data in the account is not adjusted by API queries (as is right and good).

I don't really think of it as data adjusting, more as not giving back *any* data in the cases that the API knows the data stale and guaranteed to be wrong.

**Comment by apoch** [comment]
OK, now I understand why this is not intuitive from a consumer perspective; thanks for explaining the situation!

It's a longer philosophical discussion but I'm generally not comfortable with the API implementation making judgment calls about whether or not to provide data. In my mind, providing *accurate* data means reflecting what is in the account/character database; providing *contextually meaningful* data is a separate challenge. Showing daily/dungeon reset information is definitely in the second bucket IMO.

Of course the technical compromise would be to provide last-login information for each character, and allow the consumer logic to manually ignore the daily/dungeon data if too much time has gone by. Then consumers of the API could choose if they want "DB accurate" or "intuitively accurate" data.

This runs into the historical problem of whether or not providing last-login data is something we want to  support.

**Comment by darthmaim** [comment]
Why was this closed? The issue still exists, the API can show outdated information and there is no other way (last login, …) to work around it.

**Comment by apoch** [comment]
I've explained my perspective in the comments above. There is no clear way to do anything with the issue without a lot more conversation, and there has been no conversation for a month and a half. If you would like to discuss this I am happy to reopen it.

**Comment by darthmaim** [comment]
Maybe [gitter](https://gitter.im/arenanet/api-cdi?at=5c06d0cd464b6c0fd68eed1f) is a better place to discuss this and find alternatives.
